version: "3.8"

services:
  mongo:
    image: mongo:4.2
    restart: always
    container_name: mongonumgen
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: lottogenerator
    command: [--auth]
    volumes:
      - ./data/init-mongo.js:/init-mongo.js
      - vidly:/data/db

  mongo-express:
    image: mongo-express
    restart: always  #restart the container regardless of the exit status
    depends_on:
      - mongo
    links:
      - mongo
    container_name: mongonumgenexpress
    ports:
      - 8089:8081  # port forwarding
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
#      ME_CONFIG_BASICAUTH_USERNAME: root
#      ME_CONFIG_BASICAUTH_PASSWORD: example

      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongonumgen:27017/  # mongodb://{mongo-image-username}:{mongo-image-password}@{mongo-image-name}:{port}
    volumes:
      - vidly:/data/db

volumes:
  vidly: