spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@mongo_db/lotto-web?authSource=admin  # mongodb://[username:password@]host1[:port1]/[database-name]



lotto:
  checker:
    lotteryRunOccurrence: "*/10 * * * * *"
server:
  port: 8087


