spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lottogen?authSource=admin # mongodb://[username:password@]host1[:port1]/[database-name]
#      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/lottogen?authSource=admin

#      uri: mongodb://admin:admin@mongo_db/lotto-web?authSource=admin


lotto:
  checker:
    lotteryRunOccurrence: "*/10 * * * * *"
server:
  port: 8087


