spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/lotto-generator   # mongodb://[username:password@]host1[:port1]/[database-name]



lotto:
  checker:
    lotteryRunOccurrence: "*/10 * * * * *"
server:
  port: 8087


