spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/admin  # mongodb://[username:password@]host1[:port1]/[database-name]



lotto:
  checker:
    lotteryRunOccurrence: "*/10 * * * * *"
server:
  port: 8087


